server:
    port: 8080

aws:
    credentials:
        secret: vvuldbIZtbYfn62saztzS5fxtBqc/hsXb/mI+B+a
        id: AKIAIG7E4NOYSOHGVUVA

spring:
    profiles:
        active: prod

    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
            driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
            url: jdbc:mysql://52.7.93.102:3306/app_x?useUnicode=true&characterEncoding=utf8
            name: app_x
            username: root
            password: stagGOWL123

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: Callisto

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M

callisto_config:
    datasource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
